// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// euclidean_cdist
NumericMatrix euclidean_cdist(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _sentopics_euclidean_cdist(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_cdist(A, B));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cosineSimilarity
NumericMatrix cpp_cosineSimilarity(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _sentopics_cpp_cosineSimilarity(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cosineSimilarity(A, B));
    return rcpp_result_gen;
END_RCPP
}
// wrapper_cpp_rebuild_zw
arma::imat wrapper_cpp_rebuild_zw(SEXP intTokens_, SEXP za_, arma::uword Z, arma::uword V);
RcppExport SEXP _sentopics_wrapper_cpp_rebuild_zw(SEXP intTokens_SEXP, SEXP za_SEXP, SEXP ZSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type intTokens_(intTokens_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type za_(za_SEXP);
    Rcpp::traits::input_parameter< arma::uword >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(wrapper_cpp_rebuild_zw(intTokens_, za_, Z, V));
    return rcpp_result_gen;
END_RCPP
}
// wrapper_cpp_rebuild_zd
arma::imat wrapper_cpp_rebuild_zd(SEXP za_, arma::uword Z);
RcppExport SEXP _sentopics_wrapper_cpp_rebuild_zd(SEXP za_SEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type za_(za_SEXP);
    Rcpp::traits::input_parameter< arma::uword >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(wrapper_cpp_rebuild_zd(za_, Z));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_model_module();

static const R_CallMethodDef CallEntries[] = {
    {"_sentopics_euclidean_cdist", (DL_FUNC) &_sentopics_euclidean_cdist, 2},
    {"_sentopics_cpp_cosineSimilarity", (DL_FUNC) &_sentopics_cpp_cosineSimilarity, 2},
    {"_sentopics_wrapper_cpp_rebuild_zw", (DL_FUNC) &_sentopics_wrapper_cpp_rebuild_zw, 4},
    {"_sentopics_wrapper_cpp_rebuild_zd", (DL_FUNC) &_sentopics_wrapper_cpp_rebuild_zd, 2},
    {"_rcpp_module_boot_model_module", (DL_FUNC) &_rcpp_module_boot_model_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_sentopics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
