# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euclidean_cdist <- function(A, B) {
    .Call(`_sentopics_euclidean_cdist`, A, B)
}

cpp_cosineSimilarity <- function(A, B) {
    .Call(`_sentopics_cpp_cosineSimilarity`, A, B)
}

wrapper_cpp_rebuild_zw <- function(intTokens_, za_, Z, V) {
    .Call(`_sentopics_wrapper_cpp_rebuild_zw`, intTokens_, za_, Z, V)
}

wrapper_cpp_rebuild_zd <- function(za_, Z) {
    .Call(`_sentopics_wrapper_cpp_rebuild_zd`, za_, Z)
}

cpp_minimalFrenchStemmer2 <- function(x) {
    .Call(`_sentopics_cpp_minimalFrenchStemmer2`, x)
}

cpp_minimalFrenchStemmer <- function(x) {
    .Call(`_sentopics_cpp_minimalFrenchStemmer`, x)
}

cpp_minimalFrenchStemmer3 <- function(x) {
    .Call(`_sentopics_cpp_minimalFrenchStemmer3`, x)
}

